CREATE TABLE `CLIENT` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `nom` VARCHAR(50),
  `prenom` VARCHAR(50),
  `date_naissance` DATE,
  `adresse` VARCHAR(200),
  `telephone` VARCHAR(50),
  `email` VARCHAR(50),
  `password` VARCHAR(255),
  `date_creation` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `date_modification` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `AGENCE` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `nom` VARCHAR(50)
);

CREATE TABLE `ACRISS` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `label` VARCHAR(200)
);

CREATE TABLE `LANGAGE` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `label` VARCHAR(50)
);

CREATE TABLE `OFFRE` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `ville_depart` VARCHAR(50),
  `ville_arrivee` VARCHAR(50),
  `date_depart` DATETIME,
  `date_arrivee` DATETIME,
  `tarif` FLOAT,
  `acriss_id` INT,
  `agence_id` INT
);

ALTER TABLE `OFFRE` ADD FOREIGN KEY (`acriss_id`) REFERENCES `ACRISS`(`id`);
ALTER TABLE `OFFRE` ADD FOREIGN KEY (`agence_id`) REFERENCES `AGENCE`(`id`);

CREATE TABLE `RESERVATION` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `date_paiement` DATETIME,
  `date_annulation` DATETIME,
  `date_depart` DATETIME,
  `date_arrivee` DATETIME,
  `client_id` INT,
  `offre_id` INT
);

ALTER TABLE `RESERVATION` ADD FOREIGN KEY (`client_id`) REFERENCES `ACRISS`(`id`);
ALTER TABLE `RESERVATION` ADD FOREIGN KEY (`offre_id`) REFERENCES `OFFRE`(`id`);

CREATE TABLE `SERVICECLIENT` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `nom` VARCHAR(50),
  `agence_id` INT,
  `langage_id` INT
);

ALTER TABLE `SERVICECLIENT` ADD FOREIGN KEY (`agence_id`) REFERENCES `AGENCE`(`id`);
ALTER TABLE `SERVICECLIENT` ADD FOREIGN KEY (`langage_id`) REFERENCES `LANGAGE`(`id`);

CREATE TABLE `SUJET` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `titre` VARCHAR(50),
  `date_creation` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `date_modification` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `client_id` INT,
  `serviceclient_id` INT
);

ALTER TABLE `SUJET` ADD FOREIGN KEY (`client_id`) REFERENCES `CLIENT`(`id`);
ALTER TABLE `SUJET` ADD FOREIGN KEY (`serviceclient_id`) REFERENCES `SERVICECLIENT`(`id`);

CREATE TABLE `MESSAGE` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `contenu` VARCHAR(500),
  `date_creation` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `date_modification` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `client_id` INT,
  `serviceclient_id` INT,
  `sujet_id` INT
);

ALTER TABLE `MESSAGE` ADD FOREIGN KEY (`client_id`) REFERENCES `CLIENT`(`id`);
ALTER TABLE `MESSAGE` ADD FOREIGN KEY (`serviceclient_id`) REFERENCES `SERVICECLIENT`(`id`);
ALTER TABLE `MESSAGE` ADD FOREIGN KEY (`sujet_id`) REFERENCES `SUJET`(`id`);

CREATE TABLE `CONVERSATIONVIDEOCHAT` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `date_conversation` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `client_id` INT,
  `serviceclient_id` INT
);

ALTER TABLE `CONVERSATIONVIDEOCHAT` ADD FOREIGN KEY (`client_id`) REFERENCES `CLIENT`(`id`);
ALTER TABLE `CONVERSATIONVIDEOCHAT` ADD FOREIGN KEY (`serviceclient_id`) REFERENCES `SERVICECLIENT`(`id`);
